apiVersion: apps/v1
kind: Deployment
metadata:
  name: hash-service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hash-service
  template:
    metadata:
      labels:
        app: hash-service
    spec:
      containers:
      - name: hash-service-2
        image: hash-service:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
      restartPolicy: Always